name: Deploy Static Site
on: [push]
permissions:
  pages: write
  id-token: write
jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
        - uses: actions/checkout@v3
        - uses: actions/confingure-pages@v4
        - uses: actions/upload-deploy-pages@v3
          with:
            path: ./frontend/
        - uses: actions/deploy-pages@v4


