name: Deploy Static Site
on: [push]
permissions:
  pages: write
  id-token: write
jobs:
   deploy:
     runs on: ubuntu-latest
     steps:
        -users: actions/checkout@v3
        -users: actions/confingure-pages@v4
        -users: actions/upload-deploy-pages@v3
        with:
            path:./
        -users: actions/deploy-pages@v4


